// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Zazzo.ChoresWizard2000.Data;

#nullable disable

namespace Zazzo.ChoresWizard2000.Migrations
{
    [DbContext(typeof(ChoresDbContext))]
    [Migration("20260111230916_FixColumnTypesForSqlServer")]
    partial class FixColumnTypesForSqlServer
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("Zazzo.ChoresWizard2000.Models.Chore", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AgeRestriction")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AssignToGroup")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("Frequency")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int?>("PinnedToFamilyMemberId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PinnedToFamilyMemberId");

                    b.ToTable("Chores");
                });

            modelBuilder.Entity("Zazzo.ChoresWizard2000.Models.ChoreAssignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AssignedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("ChoreId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FamilyMemberId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Month")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ChoreId");

                    b.HasIndex("FamilyMemberId");

                    b.HasIndex("Month", "Year");

                    b.ToTable("ChoreAssignments");
                });

            modelBuilder.Entity("Zazzo.ChoresWizard2000.Models.FamilyMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsParent")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsTeen")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("FamilyMembers");
                });

            modelBuilder.Entity("Zazzo.ChoresWizard2000.Models.Chore", b =>
                {
                    b.HasOne("Zazzo.ChoresWizard2000.Models.FamilyMember", "PinnedToFamilyMember")
                        .WithMany()
                        .HasForeignKey("PinnedToFamilyMemberId");

                    b.Navigation("PinnedToFamilyMember");
                });

            modelBuilder.Entity("Zazzo.ChoresWizard2000.Models.ChoreAssignment", b =>
                {
                    b.HasOne("Zazzo.ChoresWizard2000.Models.Chore", "Chore")
                        .WithMany()
                        .HasForeignKey("ChoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Zazzo.ChoresWizard2000.Models.FamilyMember", "FamilyMember")
                        .WithMany()
                        .HasForeignKey("FamilyMemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chore");

                    b.Navigation("FamilyMember");
                });
#pragma warning restore 612, 618
        }
    }
}
